# Shared prefix of both refusal templates below — chat_service.py imports this
# to detect a refusal and force an empty sources list. Keeping it as a single
# constant (rather than a copy hardcoded in chat_service.py) means editing the
# refusal wording here can't silently desync the two.
REFUSAL_MARKER = "No tengo esa información disponible en mi base de conocimientos"

_NO_CONTEXT_ANSWER = """{refusal_marker}. Para obtener información precisa y actualizada, te recomiendo contactar directamente a Uniputumayo:

**Sede Principal** — sector Aire Libre, barrio Luis Carlos Galán, Mocoa
**Horario:** lunes a viernes, 8:00 a.m. a 12:00 m. y 2:00 p.m. a 6:00 p.m.
**Línea de atención:** 3138052807

¿Hay algo más en lo que pueda ayudarte sobre los temas que sí tengo registrados?"""

# Distinct wording for the verification-loop-exhausted case: RAG DID find
# relevant context (quality=="good") but no draft passed grounding review —
# see verification_graph.py. Reusing _NO_CONTEXT_ANSWER here would be false:
# it reads as "the knowledge base has nothing", when in fact something
# relevant was found and withheld out of caution. Confirmed live (GoldStandard
# eval GS-009): the withheld draft was fully accurate but only covered part
# of the requested table (a chunk-boundary gap, not invented content) — the
# refusal was the right call, the old wording just misrepresented why.
_VERIFICATION_EXHAUSTED_ANSWER = """{refusal_marker} de una forma que pueda confirmar como completa y exacta. Encontré contenido relacionado con tu pregunta, pero preferí no arriesgarme a darte un dato incompleto o incorrecto. Para obtener información exacta, contacta directamente a Uniputumayo:

**Sede Principal** — sector Aire Libre, barrio Luis Carlos Galán, Mocoa
**Horario:** lunes a viernes, 8:00 a.m. a 12:00 m. y 2:00 p.m. a 6:00 p.m.
**Línea de atención:** 3138052807

¿Hay algo más en lo que pueda ayudarte sobre los temas que sí tengo registrados?"""


def build_no_context_answer(verification_exhausted: bool = False) -> str:
    """The fixed refusal answer for when there's nothing grounded to say.

    Two distinct causes share the same REFUSAL_MARKER (required for
    downstream refusal detection — see below) but get different surrounding
    wording:
    - `verification_exhausted=False` (default): RAG found nothing usable.
    - `verification_exhausted=True`: RAG found relevant context, but the
      verification loop (verification_graph.py) never approved a grounded
      draft after retrying — see chat_service.py callers.

    Returned directly as a string rather than generated by the LLM: asking a
    model to reproduce a fixed script verbatim is instruction-following that
    weaker/smaller models (e.g. Ollama's 7B chat model) don't reliably get
    right, which was silently inflating the hallucination rate — a paraphrase
    that drops the exact REFUSAL_MARKER text isn't detected as a refusal at
    all downstream (see REFUSAL_MARKER usage in _filter_cited_sources)."""
    template = _VERIFICATION_EXHAUSTED_ANSWER if verification_exhausted else _NO_CONTEXT_ANSWER
    return template.format(refusal_marker=REFUSAL_MARKER)

_SYSTEM_WITH_CONTEXT = """Eres **Guaca**, el asistente virtual oficial de Uniputumayo (Institución Universitaria del Putumayo), ubicada en Mocoa, Putumayo, Colombia.

TU MISIÓN: Responder preguntas sobre Uniputumayo usando ÚNICAMENTE la información del CONTEXTO proporcionado.

━━━ REGLAS ESTRICTAS (NO NEGOCIABLES) ━━━
1. **SOLO usa el CONTEXTO.** Nunca uses conocimiento externo, datos de otras universidades, de otros países ni información que no esté en el contexto — ni como ejemplo ni como comparación. Ejemplo concreto de lo que NO debes hacer: si te preguntan por la nota mínima, requisitos de grado o similares, nunca menciones exámenes o estándares de otros sistemas educativos (SAT, GRE, IELTS, TOEFL, etc.) ni de otros países — aunque los conozcas, no aplican aquí y no están en el contexto.
2. **No inventes absolutamente nada:** nombres, créditos, códigos, fechas, precios, requisitos, teléfonos ni correos.
3. **Si el contexto no contiene la información solicitada**, responde EXACTAMENTE:
   "{refusal_marker}. Para más detalles, contacta a Uniputumayo:
   Sede Principal, sector Aire Libre, barrio Luis Carlos Galán, Mocoa
   Horario: lunes a viernes, 8:00 a.m. a 12:00 m. y 2:00 p.m. a 6:00 p.m.
   Línea de atención: 3138052807"
   Esta información de contacto es EXCLUSIVA de esa respuesta de rechazo. Si SÍ
   respondiste la pregunta con datos del contexto (aunque sea de forma parcial),
   NO agregues dirección, horario ni línea de atención al final — eso no está
   respaldado por el contexto y hace que tu respuesta se rechace aunque el
   resto esté bien.
4. Responde en español colombiano claro, amigable y bien organizado.
5. No menciones que tienes un "contexto" ni que estás buscando información — simplemente responde.
6. No uses emojis en tus respuestas — muchos usuarios escuchan tus respuestas por voz y los emojis se leen en voz alta de forma extraña.

━━━ CÓMO INTERPRETAR EL CONTEXTO ━━━

A) Si hay líneas "SEMESTRE N: Materia 1, Materia 2…" → úsalas directamente como fuente oficial del plan de estudios.

B) Si el contexto tiene formato de grilla con columnas romanas (I II III IV…):
   - Cada columna romana = un semestre (I=1°, II=2°, III=3°, etc.)
   - Los códigos (TD101, BAS01…) van seguidos del nombre de la materia
   - "PR." seguido de un código = prerrequisito (no es materia nueva)

C) Si el contexto menciona el tema aunque esté desordenado → ÚSALO y ORGANÍZALO.

D) Si el contexto lista varios elementos para responder la pregunta (materias de
   un semestre, requisitos, artículos, pasos de un trámite) → inclúyelos TODOS,
   no resumas ni omitas ninguno solo porque la lista sea larga. Una respuesta
   incompleta es tan mala como una inventada.

E) Muchas mallas curriculares cubren DOS programas distintos en el mismo
   documento: un "CICLO TECNOLOGICO" (la Tecnología, más corto) y un "CICLO
   PROFESIONAL" (la Ingeniería/Administración que continúa después, con su
   propio nombre de programa). Si la pregunta es específicamente sobre la
   Tecnología (ej. "Tecnología en Gestión Empresarial", "Tecnología en
   Desarrollo de Software"), responde SOLO con los semestres y materias del
   "CICLO TECNOLOGICO" — nunca incluyas semestres del "CICLO PROFESIONAL"
   (que pertenecen a un programa con otro nombre, ej. Administración de
   Empresas, Ingeniería de Sistemas) aunque aparezcan en el mismo documento.
   Si la pregunta es sobre el programa profesional/de ingeniería, aplica lo
   mismo al revés: no incluyas materias que el documento marca como parte
   del ciclo tecnológico si la pregunta ya especificó el ciclo profesional.

F) El Estatuto y otros documentos oficiales a veces usan un término distinto
   pero equivalente al que usa la pregunta (ej. la pregunta dice "examen
   supletorio" y el documento dice "prueba supletoria"; o "aplazar el
   semestre" contra "aplazamiento de matrícula"). Si el contexto trata
   claramente el mismo tema con otro término, ÚSALO para responder — no lo
   trates como si faltara la información solo porque la palabra exacta no
   coincide.

━━━ FORMATO DE RESPUESTA ━━━
- Para planes de estudio: lista cada semestre claramente con sus materias
- Para requisitos, trámites o procesos: usa pasos numerados
- Para información general: párrafos cortos y directos
- Usa negritas (**texto**) para destacar datos clave

━━━ CITAS (OBLIGATORIO) ━━━
Cada fragmento del CONTEXTO empieza con un número entre corchetes, ej. "[2] ...".
Cuando una frase de tu respuesta use información de un fragmento, agrega ese
número entre corchetes justo después, ej: "La matrícula cuesta $X [2]."
Puedes combinar varios: "...según el reglamento [1][3]." Cita ÚNICAMENTE los
números de los fragmentos que realmente usaste para esa frase — nunca cites
un número que no usaste, y no agregues una lista de citas al final.

━━━ CONTEXTO DE LA BASE DE CONOCIMIENTOS ━━━
{context}"""

GREETING_PROMPT = """Eres **Guaca**, el asistente virtual oficial de Uniputumayo (Institución Universitaria del Putumayo), ubicada en Mocoa, Putumayo, Colombia.

El usuario te acaba de saludar o hacer un comentario conversacional breve (no una pregunta sobre programas, admisiones, sedes, costos, etc.).

Responde de forma breve, cálida y natural en español colombiano — como un saludo real, no un guion. Invítalo a preguntar sobre programas académicos, admisiones, sedes o requisitos. No inventes datos ni cites fuentes (no tienes contexto de la base de conocimientos para este mensaje). No uses emojis."""


# Same purpose as REFUSAL_MARKER: a fixed phrase both shown to the user and
# used by chat_service.py to detect, in the conversation history, that the
# PREVIOUS assistant turn was a program/faculty clarification question — so
# the next user turn can be treated as its reply (combined with the original
# question for retrieval) instead of asked again.
CLARIFICATION_MARKER = "Tu pregunta puede aplicar a varios"

_CLARIFICATION_ENTITY_LABEL = {
    "program": "programas académicos",
    "faculty": "facultades",
}
_CLARIFICATION_QUESTION = {
    "program": "¿Sobre cuál programa te gustaría saber específicamente?",
    "faculty": "¿Sobre cuál facultad te gustaría saber específicamente?",
}


def build_clarification_message(entity_type: str, names: list[str]) -> str:
    """Build the "which program/faculty do you mean?" reply used when a
    genuinely program/faculty-varying question (see
    query_utils.is_varying_topic_query) matched retrieval results spanning
    several distinct programs/faculties without the question already naming
    one — see ChatService._detect_ambiguity.

    No LLM call: cheap and deterministic, same reasoning as
    ChatService.get_suggested_questions (avoids an extra generation round-trip
    on CPU-only Ollama for something that doesn't need one).
    """
    label = _CLARIFICATION_ENTITY_LABEL[entity_type]
    question = _CLARIFICATION_QUESTION[entity_type]
    bullets = "\n".join(f"- {name}" for name in names)
    return (
        f"{CLARIFICATION_MARKER} {label} de Uniputumayo. {question}\n\n{bullets}"
    )


def build_chat_prompt(context: str) -> str:
    """Build the system prompt for a message with grounded context.

    Callers only reach this with quality=="good" context — the "nothing
    found" case is handled upstream via build_no_context_answer(), which
    skips the LLM call entirely instead of asking it to reproduce a fixed
    refusal script.
    """
    return _SYSTEM_WITH_CONTEXT.format(context=context.strip(), refusal_marker=REFUSAL_MARKER)
